### ISSUE TITLE
Wordpress trackserver plugin tslink function Fatal error

### ISSUE THREAD

**Issue by dickstoll1044** [rafaelpatro/google-customer-reviews#16]
It look like the PT-25200S is an incorrect format.  The gmt_offset is -7.  I modified the $timezone_offset instruction to make the value positive  (PT25200S) and it worked.  I've checked my WP General setting for the time setting and can not find any issues there.  A bug? 
Trackserver version is 4.2.2
Wordpress version is 5.0.3
				
I added these statement in Trackserver.php to check the values.

                                echo get_option('gmt_offset');
				echo get_option('timezone_string');

				$timezone_offset = new DateInterval( 'PT' . ( (int) get_option( 'gmt_offset' ) * 3600 ) . 'S' );

Error message plus the echo values
-7
America/Denver
Fatal error: Uncaught Exception: DateInterval::__construct(): Unknown or bad format (PT-25200S) in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\trackserver\trackserver.php:3957 Stack trace: #0 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\trackserver\trackserver.php(3957): DateInterval->__construct('PT-25200S') #1 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\trackserver\trackserver.php(3712): Trackserver->send_as_gpx(Array) #2 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\trackserver\trackserver.php(3781): Trackserver->handle_gettrack_query() #3 C:\xampp\apps\wordpress\htdocs\wp-content\plugins\trackserver\trackserver.php(2150): Trackserver->handle_gettrack() #4 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-hook.php(286): Trackserver->parse_request(Object(WP)) #5 C:\xampp\apps\wordpress\htdocs\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 C:\xampp\apps\wordpress\htdocs\wp-includes\plugin.php(515): WP_Hook->do_action(Array) #7 C:\xampp\apps\wordpress\htdocs\wp-includes\c in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\trackserver\trackserver.php on line 3957

**Comment by LuizSantos22** [comment]
@dickstoll1044 This plugin is for Magento 1 so it is not compatible with Wordpress
